### ISSUE TITLE
Setting up Repo

### ISSUE THREAD

**Issue by zcase** [mahaitongdae/steady_sim_to_real#1]
I have had some issues getting the repo up and running:

## Dependency Issues

In the README you get an error if you do the following:

```
cd steady_sim_to_real
cd deploy/envs
pip3 install -e 
```

I think it needs to be changed to:

```
cd steady_sim_to_real
cd deploy/envs/gym-pybullet-drones
git checkout dev_haitong
pip3 install -e 
```

Also it looks like there are missing dependencies. Probably should add another line that says:

```
python -m pip install gym tensorboardX seaborn
```

By default the recursive command you had doesn't check out the dev_haitong branch which causes a lot of issues. if that branch is not checked out.

**Comment by mahaitongdae** [comment]
Thank you very much! I already update the submodule and dependency accordingly.
